<?php
/*------------------------------------------------------------------------
	# SM Listing Tabs - Version 2.0.1
	# Copyright (c) 2014 YouTech Company. All Rights Reserved.
	# @license - Copyrighted Commercial Software
	# Author: YouTech Company
	# Websites: http://www.magentech.com
   -------------------------------------------------------------------------*/
   use Magento\Framework\App\Action\Action;
$helper = $this->_helper();
if ($this->_isAjax()) {
    $type_filter = $this->_getConfig('filter_type');
    switch ($type_filter) {
        case 'categories':
            $catid = $this->getRequest()->getPost('categoryid');
            $child_items = $this->_getProductInfor($catid);
            break;
        case 'fieldproducts':
            $field_order = $this->getRequest()->getPost('categoryid');
            $catid = $this->_getCatIds();
            $child_items = $this->_getProductInfor($catid, $field_order);
            break;
    }
}
if (!empty($child_items)) {
    $j = $this->getRequest()->getPost('ajax_listingtags_start', 0);
	$nb_type_show = $this->_getConfig('show_loadmore_slider');
	$nb_rows = $this->_getConfig('nb_rows', 1);
	$i = 0;$k = 0;
	$count = count($child_items);
    foreach ($child_items as $_product) {
        $i++;
        ?>
        <?php if($nb_type_show == 'slider' && ($i % $nb_rows == 1 || $nb_rows == 1)) { ?>
			<div class="ltabs-item item">
		<?php } ?>
		<?php if ($nb_type_show == 'loadmore'){ ?>
        <div class="ltabs-item new-ltabs-item">
		<?php } ?>
            <div class="item-inner">
			<?php if ($_product->_image) { ?>
				<div class="box-image">
					<a class="product-image" href="<?php echo $_product->link ?>"
					   title="<?php echo $_product->title; ?>"
						<?php echo $helper->parseTarget($this->_getConfig('target')); ?>
						>
						<img src="<?php echo $_product->_image; ?>"
							 title="<?php echo $_product->title; ?>"
							 alt="<?php echo $_product->title; ?>" >
					</a>
					
					<!--LABEL PRODUCT-->
				
					<?php
						$price = $_product->getPrice();
						$specialprice = $_product->getSpecialPrice();
						$specialPriceFromDate = $_product->getSpecialFromDate();
						$specialPriceToDate = $_product->getSpecialToDate();
									
						$today = time();
						if($price){
							$sale = round((($price-$specialprice)/$price)*100);
						}

						if ($specialprice) {
						if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
								<div class="label-product label-sale">
									<span class="sale-product-icon">
										<?php if($sale) { echo '-'.$sale.'%'; } else {echo __('Sale');} ?>
									</span>
								</div>
							<?php }
							}
						?>
					
					<?php
					$now = date("Y-m-d");
					$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
					$newsTo = substr($_product->getNewsToDate(), 0, 10);
					
					if ($newsTo != '' || $newsFrom != '') {
						if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
								<div class="label-product label-new">
									<span class="new-product-icon"><?php echo __('New'); ?></span>
								</div>
						<?php }
					} ?>
					
					<!--END LABEL PRODUCT-->							
										
									
				</div>
			<?php }?>

			<!-- Begin bs-content -->
			<?php  ?>
			<div class="box-info">
				<?php if ((int)$this->_getConfig('product_reviews_count', 1)) { ?>
						<div class="bs-review review-toptabs" style="display: none;">
							<?php 
								$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
								echo $block->getReviewsSummaryHtml($_product,$templateType,true); 
							?>
						</div>
					<?php } ?>
				<?php if ((int)$this->_getConfig('product_title_display', 1)) { ?>
					<h2 class="product-name">
						<a href="<?php echo $_product->link; ?>" title="<?php echo $_product->title; ?>"
							<?php echo $helper->parseTarget($this->_getConfig('target')); ?>
							>
							<?php echo $helper->truncate($_product->title, $this->_getConfig('product_title_maxlength')); ?>
						</a>
					</h2>
				<?php } ?>
				<?php if ((int)$this->_getConfig('product_reviews_count', 1)) { ?>
						<div class="bs-review">
							<?php 
								$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
								echo $block->getReviewsSummaryHtml($_product,$templateType,true); 
							?>
						</div>
					<?php } ?>
				
				
				<?php if ((int)$this->_getConfig('product_description_display', 1) && $helper->_trimEncode($_product->_description) != '') { ?>
					<div class="bs-description">
						<?php echo $_product->_description; ?>
					</div>
				<?php } ?>
				
				<?php if ($this->_getConfig('cat_title_display') == 1 && $this->_getConfig('product_source') != 'media') { ?>
				   <div class="bs-category"><?php echo __('Category:&nbsp') ;?>
						<a  href="<?php echo $_product->cat_link; ?>"  title="<?php echo $_product->cat_title; ?>"  <?php echo $helper->parseTarget($this->_getConfig('target')); ?>>
							 <?php echo  $helper->truncate($_product->cat_title, $this->_getConfig('category_title_max_characs', 25)); ?>
						</a>
						
					</div>
				<?php } ?>
			
				<?php /*if ($this->_getConfig('item_date_display') == 1 && $this->_getConfig('product_source') != 'media') { ?>
					<div class="bs-date">
						<?php 
						echo date('Y-m-d',strtotime($_product->created_at)); ?>
					</div>
				<?php } */ ?>
					
		
				

					<?php if ((int)$this->_getConfig('product_price_display', 1)) { ?>
						<div class="price-box">
							<div class="sale-price">
								 <?php echo $this->getProductPrice($_product); ?>
							</div>
						</div>
					<?php } ?>

			

				<?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
					<div class="bs-detail">
						<a href="<?php echo $_product->link ?>"
						   title="<?php echo $_product->title; ?>"
							<?php echo $helper->parseTarget($this->_getConfig('target')); ?>
							>
							<?php echo $this->_getConfig('product_readmore_text', 'Details'); ?>
						</a>
					</div>
				<?php } ?>
				<div class="add-info">
							
									<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && (int)$this->_getConfig('product_addwishlist_display', 1) ){ ?>
										<div class="add-wishlist">
										<a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Wishlist')); ?>"  aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist"  role="button">
                                           					 <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                       				 </a>
										</div>
							<?php } ?>	
							<?php if ((int)$this->_getConfig('product_addcart_display', 1)) { ?>
								<?php if ($_product->isSaleable()): ?>
									<?php $postParams = $this->getAddToCartPostParams($_product); ?>
									<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
										<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
										<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
										<?php echo $block->getBlockHtml('formkey')?>
										<button type="submit"
												title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
												class="action tocart primary  btn-cart">
											<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
										</button>
									</form>
								<?php else: ?>
									<?php if ($_product->getIsSalable()): ?>
										<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
									<?php else: ?>
										<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
									<?php endif; ?>
								<?php endif; ?>
								<?php } ?>

								<?php if ($block->getAddToCompareUrl() &&  (int)$this->_getConfig('product_addcompare_display', 1)){ ?>
										<?php
										$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
										?>
										<div class="add-compare">
										<a href="#"  class="action tocompare btn-action link-compare" title="<?php echo $block->escapeHtml(__('Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"  data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>' role="button">
                                        			<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                    			</a>
										</div>
									<?php }; ?>
				</div>




            </div>
        </div>
		<?php if($nb_type_show == 'slider' && ($i % $nb_rows == 0 || $i == $count)) { ?>
		</div>
		<?php }
		if ($nb_type_show == 'loadmore'){ ?>
			</div>
		<?php } ?>
	
        <?php $clear = 'clr1';
        if ($j % 2 == 0) $clear .= ' clr2';
        if ($j % 3 == 0) $clear .= ' clr3';
        if ($j % 4 == 0) $clear .= ' clr4';
        if ($j % 5 == 0) $clear .= ' clr5';
        if ($j % 6 == 0) $clear .= ' clr6';
        ?>
        <?php if( $this->_getConfig('show_loadmore_slider') == 'loadmore'){ ?>
            <div class="<?php echo $clear; ?>"></div>
        <?php } ?>
    <?php
    }
}?>